apiVersion: v1
kind: Namespace
metadata:
  name: stackrox-secured
  labels:
    clusterresourceoverrides.admission.autoscaling.openshift.io/enabled: 'true'
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '-10'
