apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: cluster-services
  namespace: stackrox-secured
spec:
  sensor:
    resources:
      requests:
        cpu: 10m
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnUpdates: true
    bypass: BreakGlassAnnotation
    contactImageScanners: ScanIfMissing
    listenOnCreates: true
    timeoutSeconds: 20
    listenOnEvents: true
  scanner:
    analyzer:
      resources:
        requests:
          cpu: 10m
      scaling:
        autoScaling: Enabled
        maxReplicas: 3
        minReplicas: 1
        replicas: 1
    scannerComponent: AutoSense
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
  clusterName: ocp-hub
  centralEndpoint: 'central-stackrox.apps.hub.cszevaco.com:443'
