apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: cluster-services
  namespace: stackrox-secured
spec:
  sensor:
    resources:
      requests:
        cpu: 10m
        memory: 1Gi
      limits:
        memory: 2Gi
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnUpdates: true
    bypass: BreakGlassAnnotation
    contactImageScanners: ScanIfMissing
    listenOnCreates: true
    timeoutSeconds: 20
    listenOnEvents: true
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 300Mi
      limits:
        memory: 1Gi
  scanner:
    db:
      resources:
        requests:
          cpu: 10m
          memory: 302Mi
        limits:
          memory: 1Gi
    analyzer:
      resources:
        requests:
          cpu: 10m
          memory: 301Mi
        limits:
          memory: 1Gi
      scaling:
        autoScaling: Enabled
        maxReplicas: 1
        minReplicas: 1
        replicas: 1
    scannerComponent: AutoSense
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
      resources:
        requests:
          cpu: 10m
          memory: 320Mi
        limits:
          memory: 750Mi
    taintToleration: TolerateTaints
  clusterName: ocp-hub
  centralEndpoint: 'central-stackrox.apps.hub.cszevaco.com:443'
