{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---

apiVersion: v1
kind: Service
metadata:
  name: puzzle2048
  namespace: exercise03-user{{ printf "%02d" (add $index 1) }}
spec:
  selector:
    app: puzzle2048
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}
{{- end }}
