apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wordle-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch",  "update", "patch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]

