{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: exercise06-user{{ printf "%02d" (add $index 1) }}
  labels:
    app: hello-world
  annotations:
    finalizers:
    - kubernetes.io/this-finalizer-doesnt-exist
spec:
  containers:
  - name: hello-world
    image: quay.io/rh_ee_cschmitz/hello-world-hostname:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 8443
        protocol: TCP
{{- end }}
{{- end }}
