{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: exercise06-user{{ printf "%02d" (add $index 1) }}
  name: my-secret
  finalizers:
    - kubernetes.io/this-finalizer-doesnt-exists
stringData:
  sensitiveKey: "top secret"

{{- end }}
{{- end }}
