{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tictactoe-vol
  namespace: exercise06-user{{ printf "%02d" (add $index 1) }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
{{- end }}
{{- end }}
