{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tictactoe
  namespace: exercise01-user{{ printf "%02d" (add $index 1) }}
  labels: {}
spec:
  to:
    kind: Service
    name: tictactoe
  tls: {}
  port:
    targetPort: 8080

{{- end }}
{{- end }}
