{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
  name: tictactoe
  namespace: exercise06-user{{ printf "%02d" (add $index 1) }}
  labels:
    app: tictactoe
    app.kubernetes.io/component: tictactoe
    app.kubernetes.io/instance: tictactoe
    app.kubernetes.io/name: tictactoe
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-namespace: exercise06-user{{ printf "%02d" (add $index 1) }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tictactoe
        deployment: tictactoe
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: tictactoe
          image: 'quay.io/rh_ee_cschmitz/tictactoe:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
{{- end }}
{{- end }}
