apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: cert-manager-operator
  labels:
    mutate-cpu: 'true'
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '0'
spec:
  finalizers:
    - kubernetes
