apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  namespace: bookinfo-mesh
  name: basic
  annotations:
    argocd.argoproj.io/sync-wave: '-50'
spec:
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  policy:
    type: Istiod
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
