apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster-workshop
spec:
  identityProviders:
  - name: htpasswd-workshop
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-my-secret-workshop
