{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: a-terminal-sandbox-user{{ printf "%02d" (add $index 1) }}
{{- end }}
{{- end }}
