apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  finalizers:
    - uninstall-helm-release
  name: stackrox-central-services
  namespace: stackrox
spec:
  central:
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
          size: 20Gi
      resources:
        limits:
          memory: 8Gi
          cpu: 1000m
        requests:
          memory: 8Gi
          cpu: 10m
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    monitoring:
      exposeEndpoint: Enabled
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 10m
        memory: 4Gi
    telemetry:
      enabled: true
  egress:
    connectivityPolicy: Online
  monitoring:
    openshift:
      enabled: true
  scanner:
    analyzer:
      resources:
        limits:
          cpu: 1000m
          memory: 1.5Gi
        requests:
          cpu: 10m
          memory: 1.5Gi
      scaling:
        autoScaling: Enabled
        maxReplicas: 1
        minReplicas: 1
        replicas: 1
    monitoring:
      exposeEndpoint: Enabled
    db:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
    scannerComponent: Enabled
