apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: gitlab-system
  labels:
    mutate-cpu: 'true'
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '-10'
