apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: rhacs-operator
spec:
  finalizers:
  - kubernetes
apiVersion: operators.coreos.com/v1
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: rhacs-operator-
  namespace: rhacs-operator
spec:
  upgradeStrategy: Default
