apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: autotesting-banner
spec:
  backgroundColor: '#36963b'
  color: '#ffffff'
  location: BannerTop
  text: Autotesting

apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: gitops-banner
spec:
  backgroundColor: '#FF5F1F'
  color: '#000000'
  location: BannerTop
  text: HUB Cluster: Argo CD / ACM / ACS / Quay
EOF
