apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ack-s3-controller
  namespace: ack-system
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: ack-s3-controller
  source: community-operators
  sourceNamespace: openshift-marketplace
