apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/joelapatatechaude/devfile-sample-python-basic
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: python-basic
    app.kubernetes.io/component: python-basic
    app.kubernetes.io/instance: python-basic
    app.kubernetes.io/name: python-basic
    app.kubernetes.io/part-of: python-basic-app
    app.openshift.io/runtime: python-basic
  name: python-basic
  namespace: multi-apps
spec:
  lookupPolicy:
    local: false
