apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/joelapatatechaude/python-hello-world
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: python-hello-world
    app.kubernetes.io/component: python-hello-world
    app.kubernetes.io/instance: python-hello-world
    app.kubernetes.io/name: python-hello-world
    app.kubernetes.io/part-of: python-hello-world
    app.openshift.io/runtime: python
  name: python-hello-world
  namespace: multi-apps
spec:
  lookupPolicy:
    local: false
