apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-logging-xyz
  namespace: openshift-logging
spec:
  targetNamespaces:
  - openshift-logging
  upgradeStrategy: Default
