apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate-staging
  namespace: openshift-ingress
spec:
  secretName: ingress-certificate-staging
  issuerRef:
    name: letsencrypt-cloudflare-staging
    kind: ClusterIssuer
  commonName: "*.apps.hub.cszevaco.com"
  dnsNames:
    - "*.apps.hub.cszevaco.com"
