---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgATQgOT4UfwFu894A9HL3CsX93fNlMeF2NyfxUGZp9kSdRxmZV6vSu2Es7hWjXWzrPkbTvhJjuhuInCxs6t8OlaWphGFRjpkHG5WduxGDDnl93Npv/wKqP4ufbPQvLem3QbieKh7E6oiCArsd5uIcUa6ssIawcqPNw7Lr8ztISoMNm2V5HFWYF4tiGlfcACmoqivIFoQnDRZn6GqZUkJpY0nfgDLfLmCayk2HtW1cc9D/iclnSgjFkASj32T35T80oDhsyh56FO/8ZAb01JeNeW8HZK31WYQd/LvlwlaEhCN00K254c+9EAe5YKg1PEXmI/6ifqdapBNe7JAalvywxasfZdFUwdd6ppiJ4XF9tY2b679jH59f6nw+s4z05/wJ8dlBDeQ4uWBoPW48Gmp0/bPGCRh/liAUSRRrxRN9CKwEoXNTSTRaSKpzsKQ3EXHXqPIOWyJpHInJqAAhvyzDyI5JjrpLWFNdJKfDYRVonv99DE9ZaC+uiX1QHNfeXcu9RhDr3g393H9tvdvsJGHNKh4rea0Dom+sq/XQLercZZMP9kfSgiHI/wrU16DgQGDB2oUBkG9pbrDh/2Y6hZq3REsfLmO8edQ2TR34sck8Tt/uG0P2I+OHteamQhcLDjinaZEcnLTpoLxHu/9hvpVK4vq0ZZxxAyndPDBwoW96s6stIEu4qyFfzh68i22d4FD0UkHvHpPAnXj91wRxeP3vIDHDasGbKKIFXkPrT51E37qwy+zqNWsO+s
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
    type: Opaque
