---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBVUuMcF+Qwn/6ezUu7HAmUg1uDSWGINRwRHDbTXF2hMqDFiBoI4Se62jI8mkDCtmrvn+N0JjPo9UNLvnQdaS0mHNoA9BNhj01GfHnAqG/b9ZdTK5t9cR/MJxu82rks8kk9DkZkjmRosqGqM09/50VF7ddFdzYbhl/ro7xs8BJmYtA0ZFH34ZBOIDCsnRK1sttrMujYBKUWHRcC/iZzdBTI0X7mPq9GQEIk3UnOSrHbIwUnu0tGWZeY7+6hqRB88J56fUZQj1WDoVGvHh7lLUHGjosNgG8Ld+UWvere+amscs5bs2l/9LwKxRKT1+yEpPE+ERDM1jGCcjtj978yD1IMMp3q9KXRGr+8ZjcE2VuRZGlnnhbDBxOg7nAEYI4ArkwKsoajRGNMPQziD587AsnI1krt+nS3Frk8sY8Q36so+BT/W5LMIjeHvbG19Ud/Pjrg8KlC09zV11SvubXS7hcmwQvJ/5b52AIg2jBVBxy0r2iWz4E2CwW/2X76FEo8Mtw92bFr8NQkpjgzIrknOZDv9+bWbgfCDriFTTEuDPToLdYVItJWy+pavibCpa6wfj1Va34mhFFSXm4BVhuOJR/VI3zAesxWjyWd4ql8pVWHIsVn4R8BSb1FcVKCfvDEyKAxc2NWumQe/paSfXQm4ECD427QHrcZYi33ODo3HJJQt1KCwh9Zk/yY4+paTC7CHweqL9T28b4zBSlpvQMhIei4QVRvNHkChGYcNnHFYW6TecBO0qBhHdHr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
