apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mediamtx
  namespace: edge
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/rh_ee_cschmitz/mediamtx:latest
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
