apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs
  namespace: openshift-gitops
spec:
  destination:
    name: hub
    namespace: default
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/acs
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
