apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-devspaces
  namespace: openshift-gitops
  labels:
    type: demo
    devspaces: demo
spec:
  destination:
    name: hub
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/applications/devspaces-multi-apps
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
  ignoreDifferences:
  - group: "*"
    kind: Deployment
    jsonPointers:
    - /spec/template/spec/containers/0/image
