apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: openshift-gitops
  labels:
    type: infrastructure
    certificates: core
spec:
  destination:
    name: hub
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/Certificates
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
      - Prune=true
      - CreateNamespace=true
