apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: openshift-gitops
  labels:
    type: infrastructure
    certificates: core
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    path: cluster-go/infrastructure/Certificates
    repoURL: https://github.com/joelapatatechaude/hub
    targetRevision: main
    helm:
      parameters:
        - name: "clustername"
          value: "$CLUSTER_NAME"
        - name: "clusterdomain"
          value: "$ROUTE53_DOMAIN"
        - name: "certmanagerdns"
          value: "$ENVIRONMENT_DNS"
        - name: "customcert"
          value: "CUSTOM_CERT"
  syncPolicy:
    syncOptions:
      - Prune=true
      - CreateNamespace=true
