apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces-gitconfig
  namespace: openshift-gitops
  labels:
    type: infrastructure
    devspaces: config
spec:
  destination:
    name: bm
  project: bm
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/DevSpaces-gitconfig
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
