apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces-che
  namespace: openshift-gitops
  labels:
    type: infrastructure
    service: DevSpaces
spec:
  destination:
    name: hub
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/DevSpaces
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
