apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: openshift-gitops
  labels:
    type: infrastructure
    bootstrap: bootstrap
    secret: core
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/ExternalSecretConfig
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    automated: {}
    syncOptions:
      - Prune=true
      - CreateNamespace=true
