apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-infra
  namespace: openshift-gitops
  labels:
    gitlab: core
spec:
  destination:
    name: in-cluster
    namespace: default
  project: hub
  source:
    path: cluster-go/infrastructure/GitLab
    repoURL: https://github.com/joelapatatechaude/hub/
    targetRevision: main
    helm:
      parameters:
        - name: "clustername"
          value: "$CLUSTER_NAME"
        - name: "clusterdomain"
          value: "$ROUTE53_DOMAIN"
