apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-operator
  namespace: openshift-gitops
  labels:
    type: operator
    gitlab: core
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/operators/GitLab
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
