apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imagepuller-operator
  namespace: openshift-gitops
  labels:
    type: operator
    devspaces: dependency
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/operators/ImagePuller
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
