apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-registry
  namespace: openshift-gitops
  labels:
    type: infrastructure
    local-registry: core
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/local-registry
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
