apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-operator
  namespace: openshift-gitops
  labels:
    type: operator
spec:
  destination:
    name: bm
  project: bm
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/operators/Logging
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
