apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-operators
  namespace: openshift-gitops
annotations:
  argocd.argoproj.io/sync-wave: "-100"
spec:
  destination:
    name: hub
    namespace: default
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/operators
    repoURL: https://github.com/joelapatatechaude/hub-go
  syncPolicy:
    automated: {}
    syncOptions:
    - Prune=true
