apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
  namespace: openshift-gitops
  labels:
    type: infrastructure
    patch: core
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/patch-operator
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
      - Prune=true
      - CreateNamespace=true
