apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay-cluster
  namespace: openshift-gitops
  labels:
    quay: core
spec:
  destination:
    name: in-cluster
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/infrastructure/Quay
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
      - Prune=true
      - CreateNamespace=true
