apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacs-central
  namespace: openshift-gitops
  labels:
    type: infrastructure
    rhacs: core
spec:
  destination:
    name: in-cluster
    namespace: default
  project: hub
  syncPolicy:
    syncOptions:
      - Prune=true
      - CreateNamespace=true
  source:
    path: cluster-go/infrastructure/rhacs-central
    repoURL: https://github.com/joelapatatechaude/hub/
    targetRevision: main
    helm:
      parameters:
        - name: "clustername"
          value: "$CLUSTER_NAME"
        - name: "clusterdomain"
          value: "$ROUTE53_DOMAIN"
