apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
  labels:
    type: infrastructure
    devspaces: dependency
spec:
  destination:
    name: bm
  project: bm
  source:
    path: cluster-go/infrastructure/sealed-secrets/base
    repoURL: https://github.com/joelapatatechaude/hub
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
