apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemesh-operators
  namespace: openshift-gitops
  labels:
    type: operator
    servicemesh: ok
spec:
  destination:
    name: hub
  project: hub
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster-go/operators/ServiceMesh
    repoURL: https://github.com/joelapatatechaude/hub
  syncPolicy:
    syncOptions:
    - Prune=true
    - CreateNamespace=true
