apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    values:
      gitlab:
        webservice:
          minReplicas: 1
          maxReplicas: 1
          replicaCount: "1"
          serviceAccount:
            name: gitlab-app-nonroot
          resources:
            requests:
              memory: 2.5G
          workerProcesses: 2
      certmanager:
        install: false
      prometheus:
        install: false
      global:
        hpa:
          minReplicas: 1
          maxReplicas: 1
        hosts:
          domain: apps.{{ .Values.clustername }}.{{ .Values.clusterdomain }}
        ingress:
          annotations:
            route.openshift.io/termination: edge
          class: none
          configureCertmanager: false
          tls:
            enabled: false
      nginx-ingress:
        enabled: false
    version: 8.1.2
