---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: openshift-devspaces
spec:
  encryptedData:
    id: AgAbNHSgpEXrdBf7/2zrvG89yeUiGpVD05rk1hg6jgPr9hndvR2xxGfxgff02V19bAHjkH9xSwm7waT71HvNDoQz/HPd31RAmkzR8ZxY9VBMxJRHhaimb/44Zs2cdSGUC+pLrBnoJLoQh52yuI15WbcWgAqgawdraTn25jHEyjMN/OuR+TYKDLO45HaPCdaeRXdLBNOZ8uYMggicnQo+Y7UF2nsGXarjxZbUicBvuZSP1bK2vBu6yNNhQVjKet65Q3CocEQkRNhgciFagUAiWXPxLdnyN8La2wC+zDJPxJR0Kt+N452uRsK1UTZazyU6z5wUkvxXwbfG/rO9JQgqxi+tf9aeHSBV0ls6LfN2DsjKVpDMquHNowWKJuk6pnZ6jTYhTogEHm++xnCNnE2mlPXD+eYSGpabXG/q8+BgotgWlRCaK66BXWNzXjehf2vNmo2ozYB5wW54AAmbQSU8SzQO90f3ZwOAZa1OpgDB4aMBfPwWAD6VlydKO7YV8Wm5idt21gvtgx1sbYpyfd30DETMApsGQFIdelLdrBZlvwtsdkM7ccxU8kS0CU0g1heUXZ6gt7U8Vz9nteDYBihp5yIXyVmDRIzKrtSjFIHDLWEKTMJk8WsILKtnlDdaS/pjr11Pig62zikUjxoNdfeeMz6fEVsYR4A7VuhNMEiL2/EzNCw5voJMxbfDq1WzGvGLhhzTX9sF0g805aGRoTQnPuFwzhaO/w==
    secret: AgA1y046ApDjIqm24N/aFUvCvszY7WzgHKozKMcA1beLhI3GYUUaIjMgLXDvxOD4XasTq2eyaJqoQN3PHB/xT3CxqXp1HYx/SiDrtY4JY+eLaC+KnO8U/5Q6G7fOjahfdGpXbo8TKeUbflR6FUD29wXNkX/yfd1/plfCZrstvXrPeYt4SxVEzENhM8KCWTH8wWSQs+FcKsEyOaOwmzhOlSZSBhc+2xDGiVZ8iCderUxeuSQ8ezRdSow8M7PvfaoJiXwgWk9HXuwAIcv6Zoe2h3pdZoyn9MkWC22D9YSD8KsM60onnKbrXPOORS0KdVZtijzE97YWn9FlsKhOr0P2py/P+rNxi0Gd+t6xKU17jAHtnX/q15Wfdjf3X9KhQurV6uxj/soU0deoSgR0RrP2BXVowdAdZa4hhhpiI3H9uXMnY4WHXYEW6p3igtk09Y0s6dJs3XKujIaEMwcbNaE19R2RJd3M0PbNby08Mq7X6S5qPB2RtgNWgSCDYp+rS5JjA6IsNPtazZWM+0JeagN5EV3vjAeYPgOuYtUdHi4fRbo2A3UREMY9VsqT316c3ELWMHj8DfyxxiK09KdM3aZ3tgQjLBJK9cypKVs/dvz6+s3twaO+Omb6BRvTRxGKx7ogB+M5IBpHCP5dlP0X94NG5kkUaxG5pngHshjcfkzeZ6GuMbQsdueW3/tZOI4+9D+NLG0GCx8qeiMIF0qc4ypZDqDhbTjInksfROsrhfupmAIAtgJUsFuN47Oy
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
        che.eclipse.org/oauth-scm-server: github
        che.eclipse.org/scm-server-endpoint: https://github.com
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: oauth-scm-configuration
        app.kubernetes.io/part-of: che.eclipse.org
      name: github-oauth-secret
      namespace: openshift-devspaces
    type: Opaque
