---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: openshift-devspaces
spec:
  encryptedData:
    id: AgBW8Eo7XUPWFBYkJXQIFIBkrDr/e89GzNFeJDDAxD0IBSPedRfx83gQevrh/iSvcoEHs6qxAZ6yLH5O3aaZvH40m1NPbB3Jd6PkjlUknnaiI180bkoMhApz2sHAp1F6WN4fxfvfCKTVJmtRwufQALRQGi4FcIHPbAaB/fXGg+pDJn+hKHtLNpm7hHApQ6sf+CU+2e5+XcGBGkF0fk18MO01UQ0TpW/2cxyIfxViuwkZLEH/P0mTaYT1WQfnyhpWEAb4/lv5UzWNvIcIzZcNfaDAMLifFmlX/Q7i6nLxVERHeKrzS0E+CHHSo7j1pTXYphBEnhnaS7uzgdSA5AiwyLcngPpP7VUg+KUwwfUDzDr9F1myK21uGiu37ar8iOQnH78xK3V8JTrmpbTvZGwGED6jp7Cp+Xrz/sN4R9337V18dl+qvgF0TJRRkDdnSkPlV4r88mRbbm0cM+NBgow00uc/gNrmbuiPB1LEVHwt6seb4Eu9mvR8qmXW0GBQjUcEID2I1jV0fdiYRRrQz0uHi/BFhJptaRKAMiwBKjGUU+Yh1S7Dt0KHS8abszGpClPWE8Ix3lp81VA9q7OLVjdeBwyj0VXvRbeaAPkhnLN4sakDumVr87cTbrsWmho6ShDQ//cAqyR/W8uPVkjL94fISpnklrBYGJQgyZz9T+gzg83VlZewVYrjTDBxAvS0kbF1idiTB+QENaTfc50tQ+GAi19suNp2PA==
    secret: AgB8InsW9TpBj/40TMagdGvrwUyPg7EmVNDKONuAeCZoLWZpcvLWGGYqPX+RVcpvHqfXfAbTDl2n48gPdfxu64Z6312LEfgisoDpf4mxOdFMNYcPAWTNdSp2Lh244SRQDgjMko35ko+JZmFP/v0yiZlIE42G8Jq0lg9lpOzEejbDGJKm8EVMm21FM2tkHJzQ+emU3ffn8Ql85bmI9eDbIDeY8b2yh4zGJg+3oyxZExi3u/EKuTF8SzcFoU99NyhKe4mnRofIR5SyxxnPXpcQeLwwgBzkfMKibbJeS2B8eNFmQET6NuPDXsuiu0V/pIAo/syoshXFEDqLQuvvwazu2aNAZvHuvvAbSCzPyLG0L9f/cPkAj3M4p21YzecSC3KbeC+qWCZhQhyyXxSLLJJ6V2zS3HuYcuspWPedb6bxsUUELZd6bHMkk/BuYM6ygcDTrpgn468T6phTEqq8zQrUMPU8Hrhw8h/CSvgQjqZlhHtE3S7VG+y+cUPubk1J8iQC/N5tb8P7tG5c5pyW8taKlqBBD6rOX9SWrvGY7MppKFUenk6QDLYYOruQvhoJW+1S3L9stZGjeJEa3GJ8NSSga/Za6yUhMUoBHHizuzaVRho31T3US0P6qrTIa1SVYRdB4XpPI3J8E0Y/5HJ4+uKGcQQ1n5qYS16YmdarEy4660tZfYZgOkh5RWT4dBhIIFsi5FdakL0BfQ1x3gvqZos7241ZMCy1MkxUCjgBSEh+0zSRtYCYh1f7S6h8
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
        che.eclipse.org/oauth-scm-server: github
        che.eclipse.org/scm-server-endpoint: https://github.com
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: oauth-scm-configuration
        app.kubernetes.io/part-of: che.eclipse.org
      name: github-oauth-secret
      namespace: openshift-devspaces
    type: Opaque
