---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: openshift-devspaces
spec:
  encryptedData:
    id: AgCKE7CnvI45LuN1H6ph0mfF7rPrdm99ATzhcITFe6SAXA99j7lugOuMHL3gpTp+3FA3pbsxxgmh7XIZoQD2y2z+UadRFgkVElaCEJk8tPq1FKhhM7yAPb7xCmhHTxI0JFUUN1FHJ/X1N9xG8k/RTN/HpxU+MmciGq5WHZuOEQ1SYw5sPQ/JnN0a5esbnanfGOa7R5PSzLmz7xl6lz/454qELdreaaPYdRsOjDzeI2hNWqEdONNWELtebD027/UafFzRmnc1IxYjWs3skqx2lrmNOHlYn+pmva7K3HUSdZEHmbM0DGK2bGkJ9vGfyUFHsYJe8EZsJcQr9TD4jY9YDbiqzpLngOQeubX9ykGM6YMs91WwtdPcUwok9klVB98YSxSydXqkWaWF4EaUuGjqNzEEEkt4pKcaadRBkgOLLXHWQw61zzEvnT2bxfPcVofjjnIw870Z4OtL4Xn9zOg4+gJVaasa11ULBF2whTbPkQR2cRWnKvfqfrICRD0jECZYfjL0JE9Rjm6EY1Z+g/q/T09z2VU69R4RX385lCEsVxtlhTrl4apaopTUbpbPr1VTON/qTzfwpOTppiSsslbNIaZ/B3lbz9QzjHZaMbLl26Ppp9sjenCAENvAwgmPPsMOKfwxrZ9b29Wo/LSRP6nIEaCBdkEXsAmXHvHDGUw/6dIAl7PM2UxJCglWeMWTy284IO5OkMv7I9eKl9yMM3hPzNehH8LBtg==
    secret: AgBCIXVeN/iChED5szfBlPrugQgD1KEmuPPgXludA2bOqfubbA2mgLOpwL/5BJMUKAROjicAJzgpwuuzP+Qqwu3MsaRGKNd1kBM8fP6cBwgJN0tnZXZiE4JOBwCQFHF7O3UqSLTov5/dU+f3prsP+/snj6GEJKGkmGBNB7Bbg2dwDKhd3SYvk52I5hq1omQ2Pm7KxaZoE8l4AGHIBXliaKTIviNkDJ0eXdq9/9vszwjyRAYIM/i2bw3u2oe0Xu5KDBlQhMG9sUii0DdihVyQfCAgk5kivrOVMEi/IxGREd1uaHMgDz00UNGuX6eT2ztSoVPw+i6U6BZ9R9YqwY60v7ED8hBbVlB+cNlX14TZN1upyphlXNyJja+N+HMI4OtqHwgiWkbvoW8E+89cU+DmWLzcCv4aJz6GtuuhJKY6WQ+AkG3kXs/lLgqFF1U/m8NeOaE91TZBnCcMbakyz4OjFXyG426H7ye4rRdEPkh9+hZ5RIyYTS3KXI0x3/+p9X88w5raNAuUHo0Y3OhZ+6QDtGKlArVgOYQOaJEtfejK+/NUMpChb6jX3XTXWb78i32X3ILo4yIW9ERb9CPyW+Sd/Bz6lLHAA1FWTYlVuLtVzfZgZN9RmXREUrnLBh6a6sR+lUFB6qKDEhMOXJqXTbrkcAjEWylHtR/A3JLN83rU+bEM6Q9go1ToR77sz4iRbPvxxtIP1/3Smwh2islelDW5A4kIyg9EGrEeBdW/nRFG3ZNgPOjLWf4PwkYK
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
        che.eclipse.org/oauth-scm-server: github
        che.eclipse.org/scm-server-endpoint: https://github.com
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: oauth-scm-configuration
        app.kubernetes.io/part-of: che.eclipse.org
      name: github-oauth-secret
      namespace: openshift-devspaces
    type: Opaque
