---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: openshift-devspaces
spec:
  encryptedData:
    id: AgBI5wPKBUFTmkAAMGpLLiDagkBgJQrfWx4EZ2lLRmiGZq5BtXzltZ+HaW4DjjosxgzG6al2Gl6NDzYBYWawWbUPI7Fl1aGbPjOaw0mXDQWjr4uXIiOc7ZllP0Ls+jIA23U05HPo4CQMAdrKm6z79lmienZpuTqA2/XiGs4ZsmNjovM25BMETxxuj50xa/gvtEb22Y2oFcmsy1j4KTz/335hXBee8PsswCVsWqnY7TR1OFtdT1HASl1JQmcrtxbXZbGrfkmOMwcHLh3GTdsjK+8N2LbkwkFNRUnKBqKdKGN94cammx9Pv002iUKNb1zQpOc2i3NNrwOCh3fBZT7vNPESDxbM9lPtllGbY6VdMPM/xvi69u/mczcovp13LIoYbHkbiYZAcxsd2DJgHqWtAfrnZY4025x+q0aaV5/uD41QXA7BoyOxI3xf4MG7nEFFMfrWhob91ZJ84ao9LLfVBoepuAy7sXIaOPeOgfjBGdn3Ntm/2du1iw3Q5Vx/3Lzl2PM1PYs7BfrMDPNUL93n9Yl8Db3NBXpTN5ulfeQjsIeIOzyj6V3PHxbTQpQNYC/7E1bD/cZ9bf8fPiZUEYKGvA/oioYmum9ztpMOyQYFfCjD3zV6MlgneAPA6Iq5Cb4RhS/tXk6cY521x4ruhv5i98ap/nKM624E26CSvtVwOYhZq62H5dzLDMT1JMFfj4xwugIRhoumpWhefiRGrmyOmQmD0eBtrw==
    secret: AgCICVOqU08cC8ATGz4k0FtIUNSwIf5PC79VstH1KlQz0JdlgBlc/htNEKVnDZ0Iph8vgRrGE9YYA6LfmCJ6YIdBVzXxfPjH5I/B8a4NaVGSJoJC1uY9lPv61hYcz7MG8qZPIJO2QtdRvCkcYhiQdLDEk2cPDeewCQQSRbzXDKfxxv8KVJ4gG3Z9/tQEmV0MgMm1h+FJyTeXwZz7sNIsMBxCnqIO/LLjjn4usHZ1GaRVlm2NL9dq/iFM6udBSTLD3pJUOXQ8FAwK6GggaDeiL/sdv7d5ouSkXMpiZstoVU4c4xl6f/eTl1cmOXFTamlJKgrxUZJTs8lMq2llzUr9pg2y1S9D/HsAp2KL00lGTSCfrPFUGiH3dKaCL1Svg6PebKwEjfJEjbrZP4ZPDlILQwBhitqdgvM31lNXiHjlBPR0MW32Hk13m03W7Jo7CuIv0zSG8CWB0fpwFd2JSXDs1Y1PT//WZ+/YiLttspxM4dohCq8I2pnNz1LlzU6RVbp5RSMMi7/lrunuetiUiD8bFmr6XC4yx7mHpOywVDzym/KRIFsKC5ZgvLcmko2DU67cevkiUAuCtNBzpIeg+qUXuMHt/sRhbw0MbxdVNaJ5x5b81R8pihjvYSB+JBX2conxzxlMw98yvyPu7GftdmdM90G+EAaj53BGdbFFHWojz2YwCp2p/NuPSF+Uz5JMbgY9FxaIIQZ11mLWJxw+GuuB0xdajwOb3Imok0+K7/iG09m+OPDbZrz0Dkrv
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
        che.eclipse.org/oauth-scm-server: github
        che.eclipse.org/scm-server-endpoint: https://github.com
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: oauth-scm-configuration
        app.kubernetes.io/part-of: che.eclipse.org
      name: github-oauth-secret
      namespace: openshift-devspaces
    type: Opaque
