---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: openshift-devspaces
spec:
  encryptedData:
    id: AgAoI6wDda33Y5eSvJfIo+poVyDjbaPZtMqHBo99U4Hb8pncjFWzu3jyAnvxi6o5I6YhN2j+34UScH64nou7Dbc813nxCt5MBr9K1GHMWx3lKRBcJN0tuPXPw17lDkx9t5yjzwFS+fy79Z8IVMR1yAdIJRhb19TIt8hc3DmmJjmDizjb5Lr6Xr+J4qLNdk2ls9K2B4sEDfoW8nmyM4M1M/C58aYcsVsiORPFhn8kKDrvLovvi+YstaFJRof1SOB3S67sn309QCqhKHI/LyJwOhKREwqsziL4+Go0uI/xYwPyZB0qQif19ZN763OBO9wyPXho5b8ZQOWxiOOky4r4z99AnPnewowSnSrT7Jt5gJ3ChFld0/hX3X1D0MFpEvIWyCWShHRIbPsDZguRxQ26BhG4JMkLZo3FH7xnX8oWuOpV7E6YPRuB2T1UtYKPN7lusnNBkFwawpof+WI4YtA1hFi6Q4HVp7P6kTWLTEFE7wp+rU44MDHM/8L34sDuFSQVwBIfYAxsEUT06BoSIlMw0RyDg/KCYw1tAkl1u2CpK1kU9XO48iC8g018Wjo9hcAzJLN1wEXYpkrJf7UKkzyIgGdW3gKKMK4SlqZsCLC2ZcxkI9VZps48yX6xuqHrjFPBwQlzevKyDdDo/+qm26ZqLiFSUBnTGW0Ad8zspj7oWJu20X9sNZFXE/KYaQxn0xQRuHJJMRY/HXHsnK9eMp1vCXpRGpwq5A==
    secret: AgBCn2Cp8s15AG2oE2PsWzLNOmwwRa95ZCm3iIy/kNUrLYQt7qDZQvZ05Ns/D8yRD+gL8wkz9d0Qq+4ZdUiGvvU4iKNZKMGTzJ8/TKjYJRwxfX/6Uiu0Dx/UhkmCKIMRb5lyLeElr9eNYmIpl5m2Y9C2fsfSnhSjoAikKmU+acXMsWX61bN4wbu86ewYbe6KU+WLD6byZprA8pIWKvKjFw8D+Kncwz396Tipv8Yc5UBYddkc8HHHlPMk15m6GAZqLbSQzgeipFWnHk0LPh3J6gziliufr1M9H1luzeao1PobTs9DerwNnt6VzwXcRvNSkq/A9pck3gZyohS+yrKSUzuvYJnDKHZm2pEHeVkRbVIiLCrhWBML+IyqHWifFGIZAoQUSfD+iqJJG6sSd1tqvG3hhtsazA76mk1RgSI6XvN4Gt2apVWKn1k6KR63DKt1P+bw18tgs81UFoST8eakdEE2zfh64UT2bPqYefZQ+8YDrED/dyMtiOYCB/EAWGizVRqf6s0RpaxFb0ziPsvNFE5a//YorZccl52VUDMCOfYhHfGOxyj9xMV2XVpAcKxnbAXufr0w3roB1kp8K82vhNJhUCZmaLsjao1qS3RUbGvagWnH9Za3CTBQ4rxVhHWdhQtRgtGcCkDajumebcoyI0UfhUE/xwMX0ljWqvMuafykuW1PFGIVOLdMH21EyVdYPNlzC2oV/7iJBNtN9lWkPWRUsRHGL6OqcbJkC24ZmOhMCI77PGGlIkcn
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
        che.eclipse.org/oauth-scm-server: github
        che.eclipse.org/scm-server-endpoint: https://github.com
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: oauth-scm-configuration
        app.kubernetes.io/part-of: che.eclipse.org
      name: github-oauth-secret
      namespace: openshift-devspaces
    type: Opaque
