---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: openshift-devspaces
spec:
  encryptedData:
    id: AgBh/sY8tpyAMqz9fkZ0xIWDGPvRFqfneDjauEhiLEvXfcg51lErWmhPSyfKCQ9T+cMICjX2VnJwMu8WtlAwDpr1Us+ZhdQqQU49HbQ80q7InYqFzOhT4y8QJOcAXHPmO/PvnpeGZD+J7m81rQingoqhn6Im9v5IAJISCQqNyz9uUu772OK0gdIRAYZSD/RSCXwdmDaCpwj5iC7Y5qwxrY2p3FJgnwuinQNgeuU3eNWG9CKz7MhX5VGMiONwq1aJ37QNrykZ1LRjICYOLm3Ne0FckaS8h4q/ouF1MzN1Wiy0W4e6luw23DlZgBMBtZ1efrZJ0R17ubP8k6eAKQDiDT/GlGmtsz2W3cEKjcB6ZY7NFF3uDrn2t1+QjIrOFoZ9Z2HpbyBiJF43hWyF2Su7QKYiKFl/F2H3PHbXXQ5bHgko83JUAP7gmAaYTBeZPo6bsrQuoIyOdEmAnIX0ozIgkDBrP3qeMA7speZL3UOapZAYW6WI9scQiHdwznDFqFkuyZHOQH5cqxRdSGjX7bK6LxwDsPmsJvtv/p5D9pkcGG01x7//jzdVxfzy4b5Gjcha3/S36TppU7upVQCT5hNMVJ9GyBN0EbN2p0QwckAYi73pMosqKgRIp/V05iDZLLfDzo0ml8qf2HD1h4V5CimVB2/00k78OAG7AEnDFXE0939lpg8p/D82JNKCFZVbXBP6chLqhWEmrHp4gLIheSTGzICfcOJRMw==
    secret: AgAavcCeUhvEcPjuyRHr0PZ3rEYW6RwoKqMUVryrHKX1W7FvTPr7bGaEnLO1MDm/JXm7D935+vNuwpSHOVF0UicxV9eSNyPddC1xA4c+VH+1Peq9S1kRHJ2iE706JcJzc49fHyKbs3ikFEBsH7loCLLpBgTz2id6J8ErIjIRcGU3y0/njmBbR9I5KPHBZn4LFPPM/o1r2R78ZJ3NAaWHQwYWVTuWjOrDFFEXvy8Xi9Qrs18fHeokWLyO9gP4E16xBnZatyianK69IyB/HvZvYVSNkT8jzoeXoCi5HsCBCX9+LdjuShE5sybmx+1ypojEs6YkYXtuahm6Eim6vZ4dUOAWGrRqqNsTRRER3Yda4SZYF6hbvzUCvP/AHhyXXW1BXr5FJ9pvqUWgnIT+HzHebOK5OBXe3ZhmrCq/icF4SttVGTzNp5TEyINbccR0MRoP5ZU7ivzYseq0wdKyOjQjaF10081fm9Jcz63r4e4L98Xhi2SorBP54PGXnoz2aRewnf7AdtutiICQyq7HUFe22+gG1v1oQrA+CfSleTpxUoHTdz10s7VkN3pifvIGsyVp0mwPTAUxuImqlA5jtRG612S6I5kcpgMtt+iCu0z0IbomAx5xWCpDloeySVDTgOE7lFoCYRZJ0F3w7Xi7bdQUTFgAO88mkBx68zR37zruc2dUUDuzslVUS/Ou/g7kE6LXMmUjQcBHgPw1lbpmWSlXRwfBlJYj8UsCBQOVOaCT2KZxocpXGRPsS6H7
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
        che.eclipse.org/oauth-scm-server: github
        che.eclipse.org/scm-server-endpoint: https://github.com
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: oauth-scm-configuration
        app.kubernetes.io/part-of: che.eclipse.org
      name: github-oauth-secret
      namespace: openshift-devspaces
    type: Opaque
