---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: openshift-devspaces
spec:
  encryptedData:
    id: AgAdvyLj0nXFoCbSampkk/2qfU3HXgyJ5Xwc2oU7IW6U7tWkdjVH+BaeyPprMjypbcix723khefUSNgH1RyP4vC2oCX37f8v9W32B4g46yv1a8MrPvBISTBzDBHJmmoYnjrELVEPjCh5yb0LhKJabTKrHQPzCGXFpUil8N5tjd7o7ZzRpqHnY4Foxh6dE5jCbMYAYlssO9XPnK9IGiFkF1K8zByEwl7/uPz5MAH2RwiPUdj+rYgFdZXG+2N+RkuVg8K194P7j34NUG5NBjGaDhhgTx5r+WkslwHlVSAXAMDlUUholRFQaj8E8kcflXe5/iXlT52gmp9rCQIpYuFZ0XFVS2lDio6idYaOjCqmguocRS+1NBaIMo/pSBLG4WMifhqsck2PXBGV4M/yLwyAkqIh1C06MPrz3wS6iodyYdQHS4fRS5gdASSomayoaKAogJufbNY77ipLjYGCDTG2J1KWhKfxz+/cuqeE5CRaPXktEW/YDf/yNKUPQkklCqi2tJKNMqUQEXQ4y+FFsDOxHEY6sNvbMSZdtgodw4aYDKZuBOE+Qbk6ZbR206zeEWf6SC5s+OZNVYe/cp4ZupYI3A4UbouGn8KD/GZlpU+cOXLiHagmpYOGZ6TrNZHxEuvuglIMM1fQlAx3ROeR+IJt81tB6qlrs6cBIYS1VBGCirMOhCVGPEQxa4JA4DOWXMxWmOmCwZ4j72MoThNOfJrBJxByVRrHMg==
    secret: AgBqulB0/b+2FwWj5q6vEOOkXQJk1Z1jHgzGxxCXFu3E83YjK7YUpF/7D+n8mDfVHKM/N1I2wsnOGC+B3XGcZPcHFkic2bO1rZnIIZlCzhhndeVhW//thV703HvQ3GoogggHFiMHuayIHDIL9Xx53DDgc/UESmaGNGei6d/kHtyokj5ZYoRp4aLuq5hGx1C/pH4nPFyyhgQ5K3YYTufnpag6poyO90R+iPDKW0jKDtV3R60ELnTxRQCWbARsp9Ppm5LxHDA2UMwsMj9PIkOw1XUJNYEjNqG5ezhbnX9ko7mD565kszXfYh92Z+qK7IoyaHuivy6UlSeTU5p1BqDnouO63OPHNWV/YmKoaS3xzj/bXO1w8jMZkclvsN1EktW+66qv55yehUnbupYVca81pjQJTIDwqK2uafJZVgo9eBwPAUbOnXuVA4htnvFoq4fq81pUwnXR3m+PGDEfakM+cTn5bQ9Um2TlHHOGYcOlfkT7p8dRfaA1A5NT4GliOWep45Iriccgyq4XS7MzFRl8ADovfsHFe6VTNzVdBKi0uMHJNWQNyHYZ9TVDkOsWlgBBZ3FfCoRTmEWre8oUIvMk5PdAX9xDyDVJKxSCX4b2ABOy1ipi3+WT5mr9GRLc1ilmMvHbf1hZJJ+uQdN9a0UtFqhcrzVJ8D7MfB/OCgEOcnGNLj+5HmIqEsvbsjwL9J8RZWdoBttxlMFKq4Ma2hUU3Q79q8OPEdzo3qBaDapXJkjJB9BZOCz0EdDj
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
        che.eclipse.org/oauth-scm-server: github
        che.eclipse.org/scm-server-endpoint: https://github.com
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: oauth-scm-configuration
        app.kubernetes.io/part-of: che.eclipse.org
      name: github-oauth-secret
      namespace: openshift-devspaces
    type: Opaque
