{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: exercise03-user{{ printf "%02d" (add $index 1) }}
spec:
  hard:
    requests.memory: 100Mi
    limits.memory: 200Mi

{{- end }}
{{- end }}
