{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exercise03-user{{ printf "%02d" (add $index 1) }}-admin-wxyz
  namespace: exercise03-user{{ printf "%02d" (add $index 1) }}
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name:  user{{ printf "%02d" (add $index 1) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end }}
{{- end }}
