apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-certificate-staging
  namespace: openshift-config
spec:
  secretName: ingress-certificate-staging
  issuerRef:
    name: letsencrypt-cloudflare-staging
    kind: ClusterIssuer
  commonName: api.{{ .Values.clustername }}.{{ .Values.clusterdomain }}
  dnsNames:
    - api.{{ .Values.clustername }}.{{ .Values.clusterdomain }}
