apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate-production
  namespace: openshift-ingress
spec:
  secretName: ingress-certificate-production
  issuerRef:
    name: letsencrypt-cloudflare-production
    kind: ClusterIssuer
  commonName: "*.apps.{{ .Values.clustername }}.{{ .Values.clusterdomain }}"
  dnsNames:
    - "*.apps.{{ .Values.clustername }}.{{ .Values.clusterdomain }}"
