{{if .Values.customcert}}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: custom-api-cert
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: patch-operator-sa
  patches:
    add-label:
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: APIServer
        name: cluster
      patchTemplate: |
        spec:
          servingCerts:
            namedCertificates:
            - names:
              - api.{{ .Values.clustername }}.{{ .Values.clusterdomain }}
              servingCertificate:
                name: ingress-certificate-production
      patchType: application/merge-patch+json
{{ end }}
