apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: clouflare-api-token-secret
  namespace: external-secrets
spec:
  externalSecretName: "cloudflare-external-secrets-generated"
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      cloudflare-api-token: yes-please
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: akeyless-cluster-secret-store

    refreshInterval: 1h
    target:
      name: cloudflare-api-token-secret
      creationPolicy: Owner
    data:
      - secretKey: api-token
        remoteRef:
          key: /openshift-hub/cloudflare-api-token
