apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: github-oauth-hub-cszevaco-joe-secret
  namespace: external-secrets
spec:
  externalSecretName: "github-oauth-hub-cszevaco-joe-secret-external-secrets-generated"
  refreshTime: "1m"
  namespaceSelector:
    matchLabels:
      github-oauth-hub-cszevaco-joe-secret: yes-please
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: akeyless-cluster-secret-store

    refreshInterval: 1h
    target:
      name: github-oauth-secret
      creationPolicy: Owner
    data:
      - secretKey: id
        remoteRef:
          key: /openshift-hub/github-oauth-hub-cszevaco-joelapatatechaude-id
      - secretKey: secret
        remoteRef:
          key: /openshift-hub/github-oauth-hub-cszevaco-joelapatatechaude-secret
