apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cron-rolebinding
  namespace: edge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cron-role
subjects:
  - kind: ServiceAccount
    name: cron-sa
    namespace: edge
