apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  finalizers:
    - uninstall-helm-release
  name: stackrox-central-services
  namespace: stackrox
spec:
  central:
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
      resources:
        limits:
          cpu: 200m
        requests:
          cpu: 200m
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    monitoring:
      exposeEndpoint: Enabled
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
    resources:
      limits:
        cpu: 200m
      requests:
        cpu: 200m
    telemetry:
      enabled: true
  egress:
    connectivityPolicy: Online
  monitoring:
    openshift:
      enabled: true
  scanner:
    analyzer:
      resources:
        limits:
          cpu: 200m
        requests:
          cpu: 200m
      scaling:
        autoScaling: Enabled
        maxReplicas: 2
        minReplicas: 1
        replicas: 1
    monitoring:
      exposeEndpoint: Enabled
    db:
      resources:
        limits:
          cpu: 200m
        requests:
          cpu: 200m
    scannerComponent: Enabled
