kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/joelapatatechaude/web-nodejs-sample'
    openshift.io/generated-by: OpenShiftWebConsole
  name: web-nodejs-sample
  namespace: multi-apps
  labels:
    app: web-nodejs-sample
    app.kubernetes.io/component: web-nodejs-sample
    app.kubernetes.io/instance: web-nodejs-sample
    app.kubernetes.io/name: web-nodejs-sample
    app.kubernetes.io/part-of: web-nodejs-sample-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
spec:
  lookupPolicy:
    local: false
