apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '-1'
spec:
  finalizers:
    - kubernetes
