kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pacman
  labels:
    tekton.dev/pipeline: pacman
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
