apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-operator-cert-managere-patcher-binding
subjects:
  - kind: ServiceAccount
    name: patch-operator-sa
    namespace: patch-operator
roleRef:
  kind: ClusterRole
  name: patch-operator-cert-manager-patcher
  apiGroup: rbac.authorization.k8s.io
