apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-operator-namespace-patcher
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "patch", "list"]
