apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-operator-ingress-patcher
rules:
  - apiGroups: ["operator.openshift.io"]
    resources: ["ingresscontrollers"]
    verbs: ["get", "patch", "list"]

