apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-operator-cert-manager-patcher
rules:
  - apiGroups: [""]
    resources: ["certmanagers"]
    verbs: ["get", "patch", "list"]
