apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-operator-api-patcher
rules:
  - apiGroups: ["config.openshift.io"]
    resources: ["apiservers"]
    verbs: ["get", "patch", "list"]
