apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-operator-cert-manager-patcher
rules:
  - apiGroups: ["operator.openshift.io/v1alpha1"]
    resources: ["certmanager"]
    verbs: ["get", "patch", "list"]
