kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: controller
  namespace: edge
  labels:
    app: controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: controller
    app.kubernetes.io/name: controller
    app.openshift.io/runtime-namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app: controller
        deployment: controller
    spec:
      volumes:
        - name: demo-cm
          configMap:
            name: demo-cm
      serviceAccountName: cron-sa
      containers:
        - name: controller
          image: quay.io/rh_ee_cschmitz/ose-cli-edge:controller
          envFrom:
            - configMapRef:
                name: demo-cm
          env:
            - name: KEY
              value: "value"
          resources:
            limits:
              cpu: 0.3
            requests:
              cpu: 0.01
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
