kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bob-admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
