{{- if .Values.userCount | int }}
{{- $userCount := .Values.userCount | int }}
{{- range $index := until $userCount }}
---

apiVersion: v1
kind: Service
metadata:
  name: pacman
  namespace: exercise01-user{{ printf "%02d" (add $index 1) }}
spec:
  selector:
    app: pacman
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}
{{- end }}
