apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo-spy
  name: bookinfo-spy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-spy
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      creationTimestamp: null
      labels:
        app: bookinfo-spy
    spec:
      containers:
      - image: quay.io/redhat-cop/tool-box
        imagePullPolicy: Always
        name: bookinfo-spy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
